collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: "8.5.0"

  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: "1.5.4"

  - name: community.mysql
    source: https://galaxy.ansible.com
    version: "3.9.0"
