- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true

- name: Push nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: true

- name: Place index
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
  become: true

- name: Ensure nginx started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
