# Vagrantfile : VM unique "awx" qui installe k3s + AWX Operator + AWX (NodePort)
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "awx"
  config.vm.network "private_network", ip: "192.168.56.120"

  # Rendre le boot plus tolérant (Windows/VirtualBox)
  config.ssh.insert_key = false
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

config.vm.provision "shell", path: "provision-awx.sh"
end