- name: Provision common baseline
  hosts: all
  gather_facts: true
  roles:
    - common
  tags: [baseline]

- name: Deploy DB
  hosts: db
  roles:
    - db
  tags: [db]

- name: Deploy Web
  hosts: web
  roles:
    - web
  tags: [web]

- name: Post-checks
  hosts: web
  gather_facts: false
  tasks:
    - name: Check HTTP
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:{{ nginx_listen_port }}/"
        return_content: true
      register: http
      failed_when: http.status not in [200]
    - debug: var=http.status

    - block:
        - name: Try to resolve DB host
          ansible.builtin.command: "getent hosts {{ groups['db'][0] }}"
          register: ge
          changed_when: false
      rescue:
        - debug:
            msg: "DB host not resolvable"
      always:
        - debug:
            msg: "Post-check completed on {{ inventory_hostname }}"
